# Generated by Django 4.2.7 on 2024-01-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_author_books_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
